KVM: VAC: Build fixes from merge (pt.1)
Still doesn't build, as h/w enable requires:
ERROR: modpost: "enable_ept" [arch/x86/kvm/xvac.ko] undefined!
ERROR: modpost: "invept_error" [arch/x86/kvm/xvac.ko] undefined!

But those are trivial features in kvm - a param and error macro.

Signed-off-by: Venkatesh Srinivas <venkateshs@chromium.org>